config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' } do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'pages/home'
  get 'pages/main'
  get 'pages/edit_user'
  root 'pages#home'
  get 'pages/profile'
  resources :posts do
    resources :comments
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :user_id, :body, :post_id, presence: true
    belongs_to :post
    belongs_to :user
  end

app/models/post.rb
class Post < ApplicationRecord
    validates :user_id, :activity, :info, presence: true
    has_many :comments, dependent: :destroy
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
    end
    def create
        puts "=================================="
        puts comment_params
        puts "=================================="
        @post = Post.find(params[:post_id])
        @comment = Comment.create(comment_params)
        redirect_to post_path(@post)
    end
    def edit
        @comment = Comment.find(params[:id, :post_id])
    end
    def update
    end
    def destroy
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
    
        respond_to do |format|
          format.html { redirect_to post_path(@post), notice: "Comment was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:user_id, :post_id, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!,  only: [:main, :profile, :edit_user]
  def home
  end
  def main
      @users = User.all
      if params[:query].present?
          @posts = Post.where("activity LIKE ?", "%#{params[:query]}%")
        else
          @posts = Post.all
        end
  end
  def profile
  end
  def edit_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
      @post = Post.new
  end
  def create
      @post = Post.new(post_params)
  
      respond_to do |format|
        if @post.save
          format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
  end

  def show
      @post = Post.find(params[:id])
      @user = User.find(@post.user_id).username
      @allUsers = User.all
      @comments = Comment.where(:post_id => params[:id])
      @newComment = Comment.new
  end

  def edit
      @post = Post.find(params[:id])
  end
  
  def update
      @post = Post.find(params[:id])
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
  end
  def destroy
      @post = Post.find(params[:id])
      @post.destroy
  
      respond_to do |format|
        format.html { redirect_to pages_main_path, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
  end
  private

  def post_params
      params.require(:post).permit(:user_id, :activity, :info, :search)
  end
  

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :sherpa])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
  
<div class= "jumbotron jumbotron-fluid bg-secondary bg-opacity-50 box-format mx-2 mb-5 pt-1 pb-1">
  <p class="lead">
    <%= username%>
  </p>

  <p class="my-4">
    <%= comment.body%>
  </p>

  <p>
  <%if current_user.id == comment.user_id%>
    <%= link_to "Destroy Comment", [comment.post, comment], class: "link_ul h6", data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  <%end%>
  </p>
  </div>

app/views/comments/_form.html.erb
<%= form_for [@post, @newComment] do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id%>
  <%= form.hidden_field :post_id, value: @post.id %>
  <p>
    <%= form.text_area :body, class: "form-control" %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SherpaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exo+2:wght@200;400;600&display=swap" rel="stylesheet">
  </head>

  <body>

    <header>
    <nav class="navbar navbar-expand-lg bg-dark">
    <div class= "container-fluid justify-content-start">
      <% if user_signed_in? %>
        <%=link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'link px-2' %>
        Welcome <%= current_user.username %>!
        <%# OR USE button_to instead of link_to but turbo is a better solution %>
      <% else %>
        <%=link_to "Login", new_user_session_path, class: 'link px-2' %>
        <%= link_to "Sign up", new_user_registration_path, class: 'link px-2' %>
      <% end %>
      </div>
    </nav>
    <% if notice != "" && notice != nil %>
    <p class="alert alert-warning"><%= notice %></p>
    <% end %>
    <% if alert != "" && alert != nil %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    </header>
  <div class = "container-fluid">
    <%= yield %>
  </div>
  <footer class="bg-dark">
  <p>By AZ-LCA March 2023 - Find me on Github and LinkedIn under the same @!</p>
  <footer/>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "page-header header" >
<h1>HOME</h1>
</div>
<hr class="my-4">
<br/>
<div class = "navbar justify-content-start h4 mx-2" >
<% if user_signed_in? %>
<%= link_to "Profile Details",  pages_profile_path, class: "link"%>
&nbsp;|&nbsp;
<%= link_to "Sherpa Listings", pages_main_path, class: "link"%>
<% end %>
</div>
<br/>
<br/>
<div class="jumbotron mx-2 jumbotron-fluid bg-secondary bg-opacity-50 box-format">
<pre class="chroma">
<p class = "display-4" >Welcome!</p>
<p class = "lead" >This website is made for Destiny 2.<br/><br/>Find sherpas willing to go through specific dungeons and raids!</p>
</pre>
</div>

app/views/pages/main.html.erb
<div class = "page-header header" >
<h1>SHERPA LISTINGS</h1>
</div>
<hr class="my-4">
<br/>
<div class = "navbar justify-content-start h4 mx-2" >
<%= link_to "Return", pages_home_path, class: "link_ul" %>
&nbsp;|&nbsp;
<%= link_to "Profile Details", pages_profile_path, class: "link_ul" %>
</div>
<br/>
<br/>
<div class= "container-fluid">
<% if current_user.sherpa == true %>
<%= link_to "New post", new_post_path, class: "h4 link_ul" %>
<% end %>
<br/>
<br/>
<%= form_with(url: pages_main_path, method: :get, data: {turbo_frame: "pages"}) do |form| %>

  <%= form.label :query, "Search by activity name:", class: "h4" %>
  <br/>
  <br/>
  <div>
    <%= form.select :query, options_for_select(["King's Fall", 
    'Vault Of Glass', 
    'Vow of the Disciple', 
    'Deep Stone Crypt', 
    'Garden of Salvation', 
    "Last Wish", 
    "Spire of the Watcher", 
    'Duality', 
    'Grasp of Avarice', 
    'Prophecy', 
    'Pit of Heresy', 
    'Shattered Throne' ]) %>
    <%= form.submit 'Search', class: "btn btn-light margin" %>
  </div>
<% end %>
<br>
<br>
<% @posts.each do |post| %>
    <div class= "jumbotron jumbotron-fluid bg-secondary bg-opacity-50 box-format mx-2 mb-5">
    <div id="post">
      <%= render "posts/post", post: post, username: @users.find(post.user_id).username %>
      <p>
          <%= link_to "Details", post, class: "link_ul h4" %>
      </p>
    </div>
    </div>
<% end %>

</div>

app/views/pages/profile.html.erb
<div class = "page-header header" >
<h1>PROFILE</h1>
</div>
<hr class="my-4">
<br/>
<div class = "navbar justify-content-start h4 mx-2" >
<%= link_to "Return", pages_home_path, class: "link_ul" %>
&nbsp;|&nbsp;
<%= link_to "Sherpa Listings", pages_main_path, class: "link_ul" %>
</div>
<br/>
<br/>
<div class= "jumbotron jumbotron-fluid bg-secondary bg-opacity-50 box-format mx-2 mb-5 pb-5">
<p class= "display-4"><%=current_user.username%></p>
<p class= "lead">Email: <%=current_user.email%></p>
<%=link_to "Edit User", edit_user_registration_path, class: "link_ul lead"%>
</div>

app/views/posts/_form.html.erb
<div class= "jumbotron jumbotron-fluid bg-secondary bg-opacity-50 box-format mx-2 mb-5 pb-5">
<%= form_with(model: post) do |form|%>
  <br/>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.hidden_field :user_id, value: current_user.id%>
  </div>
  <div>
    <%= form.label :activity, style: "display: block", class: "lead"%>
    <%= form.select :activity, options_for_select(["King's Fall", 'Vault Of Glass', 'Vow of the Disciple', 'Deep Stone Crypt', 'Garden of Salvation', "Last Wish", "Spire of the Watcher", 'Duality', 'Grasp of Avarice', 'Prophecy', 'Pit of Heresy', 'Shattered Throne' ])%>
  </div>
  <div>
    <%= form.label :info, style: "display: block", class: "lead"%>
    <%= form.text_field :info, class: "form-control"%>
  </div>
  </br>
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= post %>">
  <p>

  <div class="display-4">
    <%= post.activity %>
  </div>
    <br/>
  <div class="lead">
    <strong>Post by:</strong>
    <%= username %>
    <br/>
    <br/>
    <p class="h4">Description</p>
    <br/>
    <%= post.info %>
  </div>
  </p>
</div>

app/views/posts/edit.html.erb
<div class = "page-header header" >
<h1>Edit Post</h1>
</div>
<hr class="my-4">
<br/>
<div class = "navbar justify-content-start h4 mx-2" >
<%= link_to "Back To Post Details", post_path(@post), class: "link_ul"%>
</div>
<br/>
<%= render "form", post: @post %>
<br>
<div class= "container-fluid">
<%= button_to "Delete post", post_path(@post), class: "button", data: { 
  confirm: "Are you sure?", turbo_confirm: "Are you sure?" 
  }, method: :delete 
%>
</div>

app/views/posts/new.html.erb
<div class = "page-header header" >
<h1>NEW POSTING</h1>
</div>
<hr class="my-4">
<br/>
<div class = "navbar justify-content-start h4 mx-2" >
<%= link_to "Back To Sherpa Listings", pages_main_path, class: "link_ul"%>
</div>
<br/>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class = "container-fluid page-header header" >
<h1>Post Details</h1>
</div>
<hr class="my-4">
<br/>
<div class= "container-fluid">
<div class = "navbar justify-content-start h4 mx-2" >
<%= link_to "Back To Sherpa Listings", pages_main_path, class: "link_ul"%>
</div>
<br/>
<br/>
<div class= "jumbotron jumbotron-fluid bg-secondary bg-opacity-50 box-format mx-2 mb-5">
<%= render "post", post: @post, username: @user %>

<% if current_user.username == @user %>

<%= link_to "Edit Post", edit_post_path, class: "link_ul" %>

<% end %>
</div>
<div class = "page-header header" >
<h2>Comments:</h2>
</div>
<hr class="my-4">
<div class="container-fluid">
<% @comments.each do |comment| %>
<% if comment.user_id != nil %>
<%= render "comments/comment", comment: comment, username: @allUsers.find(comment.user_id).username  %>
<% end %>
<% end %>
<div class= "jumbotron jumbotron-fluid bg-secondary bg-opacity-50 box-format mx-2 mb-5 pb-5">
<h2 class="display-5">Add a comment:</h2>
<%= render 'comments/form' %>
</div>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "link_ul" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "link_ul" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "link_ul" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "link_ul" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "link_ul" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>